"""Added teacher table2

Revision ID: 3aded3440b49
Revises: 
Create Date: 2016-08-20 23:04:26.797166

"""

# revision identifiers, used by Alembic.
revision = '3aded3440b49'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
