"""Added teacher table2

Revision ID: 51642abbea69
Revises: 3aded3440b49
Create Date: 2016-08-20 23:05:16.370605

"""

# revision identifiers, used by Alembic.
revision = '51642abbea69'
down_revision = '3aded3440b49'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
